//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XRMS.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class CodeDefinitionEntity
    {
        public string Type { get; set; }
        public string Prefix { get; set; }
        public long LastIndex { get; set; }
        public Nullable<byte> Increment { get; set; }
    }
}
