
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace XRMS.Data.EntityFramework
{

using System;
    using System.Collections.Generic;
    
public partial class MaterialLogEntity
{

    public long LogCounter { get; set; }

    public int MaterialId { get; set; }

    public string Actor { get; set; }

    public System.DateTime LogDatetime { get; set; }

    public byte Action { get; set; }

    public decimal CurrentAmount { get; set; }

    public decimal NewAmount { get; set; }

}

}
