
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace XRMS.Data.EntityFramework
{

using System;
    using System.Collections.Generic;
    
public partial class MaterialEntity
{

    public int Id { get; set; }

    public string Code { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public int GroupId { get; set; }

    public int UnitId { get; set; }

    public decimal Amount { get; set; }

    public decimal UsageAmount { get; set; }

    public System.DateTime ConfirmationDate { get; set; }

    public decimal LastConfirmationAmount { get; set; }



    public virtual MaterialGroupEntity MaterialGroup { get; set; }

}

}
