//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XRMS.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderEntity
    {
        public long Id { get; set; }
        public string Code { get; set; }
        public int TableId { get; set; }
        public int CreatorId { get; set; }
        public byte State { get; set; }
        public System.DateTime OrderDatetime { get; set; }
        public System.DateTime EditDatetime { get; set; }
        public System.DateTime BillDatetime { get; set; }
        public System.DateTime CheckoutDatetime { get; set; }
        public decimal SubTotalPrice { get; set; }
        public decimal TotalPrice { get; set; }
        public decimal ServiceCharge { get; set; }
        public bool VatEnable { get; set; }
        public decimal VatPrice { get; set; }
        public byte DiscountPercent { get; set; }
        public decimal DiscountPrice { get; set; }
        public decimal SpecialDiscount { get; set; }
        public decimal Cash { get; set; }
        public decimal Change { get; set; }
        public bool LockState { get; set; }
        public int LockKeeperId { get; set; }
        public byte PrintCount { get; set; }
        public bool IsCancelled { get; set; }
        public string CancelReason { get; set; }
        public long ReportCounter { get; set; }
    }
}
