//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XRMS.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItemEntity
    {
        public byte Sequence { get; set; }
        public long OrderId { get; set; }
        public int ProductId { get; set; }
        public int Quantity { get; set; }
        public System.DateTime CreateDatetime { get; set; }
        public byte State { get; set; }
        public bool IsCancelled { get; set; }
        public bool IsAlwaysReady { get; set; }
        public System.DateTime StartDatetime { get; set; }
        public System.DateTime StopDatetime { get; set; }
        public System.DateTime ServeDatetime { get; set; }
    }
}
