//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XRMS.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductEntity
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int UnitId { get; set; }
        public int GroupId { get; set; }
        public decimal Price { get; set; }
        public byte[] Image { get; set; }
        public bool IsAlwaysReady { get; set; }
    }
}
