//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XRMS.Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportMaterialEntity
    {
        public long ReportCounter { get; set; }
        public byte OrderItemSequence { get; set; }
        public string MaterialCode { get; set; }
        public string MaterialName { get; set; }
        public decimal Amount { get; set; }
        public string UnitName { get; set; }
    }
}
