
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace XRMS.Data.EntityFramework
{

using System;
    using System.Collections.Generic;
    
public partial class ReportEventEntity
{

    public long ReportCounter { get; set; }

    public int EventCounter { get; set; }

    public System.DateTime EventDate { get; set; }

    public int EventClass { get; set; }

    public string Text { get; set; }

}

}
